### ISSUE TITLE
Install a docker-compose that works with Ansible's docker_service

### ISSUE THREAD

**Issue by LunkRat** [geerlingguy/ansible-role-docker#129]
When I run this role with `docker_install_compose: true` and then try to run a subsequent [docker_service](https://docs.ansible.com/ansible/latest/modules/docker_service_module.html) task:

```
FAILED! => {"changed": false, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose"}
```
Issue #53 mentions that this role does not leave the target machine with a `docker-compose` that will work with Ansible's `docker_service`. 

How to fix that?

**Comment by pescobar** [comment]
@robjuffermans the problem with that workaround is that after doing `pip install docker-compose` you get a binary `/bin/docker-compose` and then you hit this other issue that breaks idempotence https://github.com/geerlingguy/ansible-role-docker/issues/88

the only workaround I found when I need to use the `docker_service` module in ansible is to "manually" align the versions like this:

```
- name: install pip
  include_role:
    name: geerlingguy.pip
    apply:
      become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose==1.22.0
```

you have to double check that the version installed from pip matches the [version installed by this role](https://github.com/geerlingguy/ansible-role-docker/blob/master/defaults/main.yml#L14)
