### ISSUE TITLE
CentOs module docker_login get Failed to import docker 

### ISSUE THREAD

**Issue by stkac** [geerlingguy/ansible-role-docker#134]
Does someone know how to fix it? 
thanks in advance,
```
- name: Log into private registry and force re-authorization
  docker_login:
    registry: cr.domain.tld
    username: '{{ dockerUsername }}'
    password: '{{ dockerPassword }}'
    reauthorize: yes

```

`FAILED! => {"changed": false, "msg": "Failed to import docker or docker-py - No module named requests.exceptions. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}
`
