### ISSUE TITLE
Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)

### ISSUE THREAD

**Issue by dnk8n** [geerlingguy/ansible-role-docker#159]
Examples of this kind of error: https://gitlab.com/kositribe/deployments/-/jobs/300195241

You can see it happens quite consistently in the case where I use Hetzner Cloud, but I have never seen it happen when using AWS.

Also, there have been cases where it just happened to successfully pass even while on Hetzner.

The workaround which avoids this specific lock related error from occuring is, at top of playbook:

```
- name: Wait until system is ready
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for apt list lock (Known to cause issues sometimes)
      raw: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done
```

Is it not possible to make the role able to wait if necessary, so that this kind of codeblock would be unnecessary?

Surely this should actually belong in apt module. If you agree, you might know where I should recreate / find an existing issue about this?
