### ISSUE TITLE
apt_key permission issue

### ISSUE THREAD

**Issue by kovkev** [geerlingguy/ansible-role-docker#160]
Hi! Thanks tons for this repository.

I'm not sure if this is an issue with ansible-role-docker or with ansible's apt_key module. I find that there's an error when running ansible (having packer configuring an AMI using ansible), in my specific situation:

Pardon the file type here, but using my build tools, these compile:
playbook_master.jsonnet:

```
{
machine (type = 'master'):: [
  {
    hosts: 'all',
    become: 'yes', # adding or removing this doesn't help
    vars: {
      kubernetes_allow_pods_on_master: true,
      kubernetes_role: type,
    },
    roles: [{
      role: 'geerlingguy.docker',
    }, {
      role: 'geerlingguy.kubernetes',
      become: 'yes'
    }]
  }
]
}
```

packer.json (not sure if this is helpful):

```
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
        "root-device-type": "ebs"
      },
      "owners": ["099720109477"],
      "most_recent": true
    },
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-example {{timestamp}}"
  }],
  "provisioners": [{
      "type": "ansible",
      "user": "root",
      "playbook_file": "files/playbook_master.json",
      "extra_arguments": [ "-vvvv" ]
    }, {
      "type": "shell",
      "inline": [
        "echo Thanks to https://alex.dzyoba.com/blog/packer-for-docker/ and make sure to use jsonnet to properly share the configuration."
      ]
    }
  ]
}
```

And finally, the verbose run (without my AWS keys):  https://pastebin.com/yKML59LY (410 lines)

There are two errors: 
```
 A -            amazon-ebs:     "cmd": "/usr/bin/apt-key add -",
       does   amazon-ebs:     "msg": "ERROR: This command can only be used by root.",
```

```
B -            amazon-ebs:     "cmd": "set -o pipefail\ncurl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -\n",
      does   amazon-ebs:         "/bin/sh: 1: set: Illegal option -o pipefail"
```

I'd like tot focus on the first one (A) which says that apt-key can only be used by root. The thing is, I use "become: 'yes'" and all sorts of other variables in the playbook on that block: become_user, become_method, and remote_user, all pointing for maximum permissions: "root", "sudo", and "root". And I still get a permission error. I think that SSH'ing as root is successful, as you can see in the logs a little bit above the error.

For the second issue (B), I think it's because `pipefail` is not an option you can set using `set` if you're in /bin/sh. It would work inside /bin/bash.

Please recognize the issue with A! I'll keep looking on my side.

Thank you!

Kevin

**Comment by geerlingguy** [comment]
I think for `a` you would need to also use `become: yes` with the

```
role: 'geerlingguy.docker',
```

Just like you do for the `geerlingguy.kubernetes` role. A lot of Docker requires root, and running the role as any other user would not be able to install everything correctly.

**Comment by kovkev** [comment]
I think the issue is that when packer sets up the machine using ansible,
the machine starts a process to updates many packages. It grabs a lock
somewhere. And the permission error message is not the best, it should
mention the lock (I think you can't take the lock even if you're running as
sudo). As part of your roles, apt-key itself tries to hold that lock.

The solution for me will be two-fold: Use the latest builds for a Ubuntu
Xenial version (like 20190913) for example, and add in the ansible playbook
a section where we run a loop and wait for the updates to install. Do you
think those latest uldates are necessary for security purposes? Or are all
security fixed always part of a main ubuntu build?

**Comment by kovkev** [comment]
```
tasks: [{
      name: 'Wait for any possibly running unattended upgrade to finish',  
      shell: "while pgrep unattended; do wc /var/log/unattended-upgrades/unattended-upgrades-dpkg.log; sleep 10; done;"
      # systemd-run --property='After=apt-daily.service apt-daily-upgrade.service' --wait /bin/true"
    }
```

What do you think of a command like this? One issue I am having is that I cannot see the progress on the build. I'm using bazel, packer, ansible together. What I see is:

```
    amazon-ebs: META: ran handlers
    amazon-ebs:
    amazon-ebs: TASK [Wait for any possibly running unattended upgrade to finish] **************
    amazon-ebs: task path: /private/var/folders/tj/tshgns294mbd2qlh8zg4wj4m0000gp/T/tmpd3VJoqdeploy_packer/files/playbook_master.json:9
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=59021 -o 'IdentityFile="/var/folders/tj/tshgns294mbd2qlh8zg4wj4m0000gp/T/ansible-key891173850"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/kevin/.ansible/cp/264b1eb8c4 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/${USER}/ansible/ansible-tmp-1570073167.959287-160878915880627 `" && echo ansible-tmp-1570073167.959287-160878915880627="` echo /tmp/${USER}/ansible/ansible-tmp-1570073167.959287-160878915880627 `" ) && sleep 0'"'"''
    amazon-ebs: <127.0.0.1> (0, b'ansible-tmp-1570073167.959287-160878915880627=/tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627\n', b'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/kevin/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 52: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 71902\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
    amazon-ebs: Using module file /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible/modules/commands/command.py
    amazon-ebs: <127.0.0.1> PUT /Users/kevin/.ansible/tmp/ansible-local-71894ae5tmxd7/tmp17741ezl TO /tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/AnsiballZ_command.py
    amazon-ebs: <127.0.0.1> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=59021 -o 'IdentityFile="/var/folders/tj/tshgns294mbd2qlh8zg4wj4m0000gp/T/ansible-key891173850"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/kevin/.ansible/cp/264b1eb8c4 /Users/kevin/.ansible/tmp/ansible-local-71894ae5tmxd7/tmp17741ezl '[127.0.0.1]:/tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/AnsiballZ_command.py'
    amazon-ebs: <127.0.0.1> (0, b'', b'Executing: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command scp -v -t /tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/AnsiballZ_command.py\nOpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/kevin/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 52: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 71902\r\ndebug3: mux_client_request_session: session request sent\r\nSending file modes: C0600 105459 tmp17741ezl\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=59021 -o 'IdentityFile="/var/folders/tj/tshgns294mbd2qlh8zg4wj4m0000gp/T/ansible-key891173850"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/kevin/.ansible/cp/264b1eb8c4 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/ /tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/AnsiballZ_command.py && sleep 0'"'"''
    amazon-ebs: <127.0.0.1> (0, b'', b'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/kevin/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 52: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 71902\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=59021 -o 'IdentityFile="/var/folders/tj/tshgns294mbd2qlh8zg4wj4m0000gp/T/ansible-key891173850"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/Users/kevin/.ansible/cp/264b1eb8c4 -tt 127.0.0.1 '/bin/sh -c '"'"'/usr/bin/python3 /tmp/ubuntu/ansible/ansible-tmp-1570073167.959287-160878915880627/AnsiballZ_command.py && sleep 0'"'"''
```
