### ISSUE TITLE
how to install docker 18.09.8 both ubuntu and centos ?

### ISSUE THREAD

**Issue by Sn0rt** [geerlingguy/ansible-role-docker#162]
how to install specify version docker?

ubuntu

```
docker_package: "docker-{{ docker_edition }}-18.09"
```

```
    ubuntu-1804:
    ubuntu-1804: TASK [geerlingguy.docker : Install Docker.] ************************************
    ubuntu-1804: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce-18.09' is available"}
    ubuntu-1804:
```

can't get this point

>The docker_edition should be either ce (Community Edition) or ee (Enterprise Edition). You can also specify a specific version of Docker to install using the distribution-specific format: Red Hat/CentOS: docker-{{ docker_edition }}-<VERSION>; Debian/Ubuntu: docker-{{ docker_edition }}=<VERSION>.

can some one paste a example ?
