### ISSUE TITLE
Buster: failing task Install Docker Compose using Pip

### ISSUE THREAD

**Issue by IoTPlay** [geerlingguy/ansible-role-docker#163]
It fails at this step: `TASK [geerlingguy.docker_arm : Install Docker Compose using Pip.] `See errors:
[error.txt](https://github.com/geerlingguy/ansible-role-docker/files/3721921/error.txt)

My playbook:
```

- hosts: all
  become: true

  name: Install docker with roles from geerlingguy https://galaxy.ansible.com/geerlingguy/docker_arm 

  vars:
    pip_install_packages:
      - name: docker

  roles: 
    - geerlingguy.pip
    - geerlingguy.docker_arm

```
