### ISSUE TITLE
docker_install_compose does not work

### ISSUE THREAD

**Issue by hasufell** [geerlingguy/ansible-role-docker#168]
Throws:

```
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on ip-xxx's Python /usr/bin/python3. Please read module documentation and install in the appropriate location, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"}
```

Task for docker was:

```
    - name: install docker
      become: yes
      import_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: true
        docker_users:
          - "{{ ansible_user }}"
```

Task it failed on was:

```
    - name: Tear down services
      docker_compose:
        project_src: ~/foo
        build: no
        state: absent
```

Distro is ubuntu bionic.
