### ISSUE TITLE
[centos] specify docker-cli version

### ISSUE THREAD

**Issue by pan1c** [geerlingguy/ansible-role-docker#179]
Hi!

`yum install docker-ce-18.09.6`
Leads to installing latest version of docker-ce-cli 
```
rpm -qa | grep docker
docker-ce-cli-19.03.5-3.el7.x86_64
docker-ce-18.09.6-3.el7.x86_64
```
And if you want to install "docker-ce-cli-18.09.6" of the same version you should specify it 
`yum install docker-ce-18.09.6 docker-ce-cli-18.09.6`

Would you be so kind add playbook functionality to specify docker-ce-cli version as same as docker-ce version?

eg
```
- name: Install Docker CLI.                                                                                                                                                                                                                  
  package:                                                                                                                                                                                                                                   
    name: "{{ docker_cli_package }}"                                                                                                                                                                                                         
    state: "{{ docker_cli_package_state }}"                                                                                                                                                                                                  
  notify: restart docker      
```
and
```
docker_cli_edition: 'ce'                                                                                                                                                                                                                     
docker_cli_package: "docker-{{ docker_edition }}-cli"                                                                                                                                                                                        
docker_cli_package_state: present 
```
Thank you!
