### ISSUE TITLE
systemd.unified_cgroup_hierarchy=0 kernel param for FC31 (and other CGroupsV2 distros)

### ISSUE THREAD

**Issue by westurner** [geerlingguy/ansible-role-docker#186]
e.g. docker-compose does not work in F31+ due to docker not yet supporting cgroupsv2. It's necessary to modify the kernel params in /etc/default/grub and reboot:

```yaml
- hosts: localhost
  # https://fedoraproject.org/wiki/Changes/CGroupsV2
  name: Fix docker on Fedora 31+ (CGroupsv2 -> CGroupsv1)
  become: true
  gather_facts: yes
  tags: ["docker", "cgroupsv1"]
  tasks:
    - name: Add systemd.unified_cgroup_hierarchy=0 line to /etc/default/grub
      lineinfile:
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=".*?)( systemd\.unified_cgroup_hierarchy=0)?"$'
        line: '\1 systemd.unified_cgroup_hierarchy=0"'
        backrefs: yes
      register: line_result
      when:
        ansible_distribution == "Fedora" and ansible_distribution_major_version > '30'
    - name: Rebuild grub
      command: "grub2-mkconfig"
      when:
        - line_result.changed
    - name: Reboot after modifying /etc/default/grub
      reboot:
      when:
        - line_result.changed
```

References regarding the coming of CGroupsV2:
- https://fedoraproject.org/wiki/Changes/CGroupsV2
- https://www.reddit.com/r/Fedora/comments/dqgztf/docker_is_not_available_in_fedora31_by_default/

**Comment by westurner** [comment]
... That newish `reboot:` task is :trophy:  ( https://www.jeffgeerling.com/blog/2018/reboot-and-wait-reboot-complete-ansible-playbook )

**Comment by davidalger** [comment]
Just as an FYI, the above will not always result in exactly the same outcome of running the following (as documented for F31):
```
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
```

On a system I'm working with right now (completely clean install):

```
root@hylfing:03:21 PM:~# grep unified_cgroup_hierarchy /etc/default/grub 
root@hylfing:03:22 PM:~# grep unified_cgroup_hierarchy /boot/grub2/grubenv 
kernelopts=root=/dev/mapper/vgfedora-root ro resume=/dev/mapper/vgfedora-swap rd.lvm.lv=vgfedora/root rd.lvm.lv=vgfedora/swap rhgb quiet systemd.unified_cgroup_hierarchy=0
```

Just posting this here so when the above can be formed into an update to this role, hopefully it can account for this. I'm not currently familiar enough with everything grub related to know why grubby puts it there vs in /etc/default, but it does.

**Comment by westurner** [comment]
That regex could definitely be better. It does presume that `systemd.unified_cgroup_hierarchy=?` is at the end of the line, and will dumbly add another `systemd.unified_cgroup_hierarchy=1` to the end of the line.

It may be better to run grubby whenever `systemd.unified_cgroup_hierarchy=1` is not in `/etc/default/grub`?

**Comment by westurner** [comment]
Sure would be nice to get CGroupsv2 support into docker so that this workaround isn't necessary to get Docker to work on Fedora 31+.

I don't recall specifically what features we forego by dropping back to CGroupsv1? Nested rootless containers?

**Comment by davidalger** [comment]
> Sure would be nice to get CGroupsv2 support into docker so that this workaround isn't necessary to get Docker to work on Fedora 31+

Agreed 💯 

> That regex could definitely be better. It does presume that systemd.unified_cgroup_hierarchy=? is at the end of the line

True, although the regex specificity is a slightly different issue than what I was mentioning. What I'm saying is when using `grubby` to set the kernelopt the value is not added to `/etc/default/grub` at all. It is only added to `/boot/grub2/grubenv`

This is what I came up with last night to deploy Docker via Ansible on the F31 setup I was working on last night:

`playbook.yml`
```yaml
- hosts: hylfing
  become: yes

  handlers:
    - name: reboot machine
      reboot: reboot_timeout=600

  pre_tasks:
    - import_tasks: tasks/cgroupsv1.yml

    - name: Immediately notify handlers to enforce kernel updates or changes to kernelopts
      meta: flush_handlers

  roles:
    - geerlingguy.docker

```

`tasks/cgroupsv1.yml`
```yaml
# Cgroups Exception For Fedora 31
# 
# https://fedoraproject.org/wiki/Changes/CGroupsV2
# https://fedoraproject.org/wiki/Common_F31_bugs#Other_software_issues
#
# https://github.com/geerlingguy/ansible-role-docker/issues/186
# 
---
- name: Install grubby
  dnf:
    name: grubby
    state: present
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= '31'
  tags: [docker, cgroupsv1]

- name: Check if systemd.unified_cgroup_hierarchy=0 is set in kernelopts
  command: grep -Eq '^kernelopts=.* systemd\.unified_cgroup_hierarchy=0' /boot/grub2/grubenv
  register: grubenv_has_cgroup_exception
  check_mode: no
  ignore_errors: yes
  changed_when: no
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= '31'
  tags: [docker, cgroupsv1]

- name: Configure systemd.unified_cgroup_hierarchy=0 in kernelopts
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when:
   - ansible_distribution == "Fedora" and ansible_distribution_major_version >= '31'
   - grubenv_has_cgroup_exception.rc != 0
  tags: [docker, cgroupsv1]
  notify: reboot machine
```
