### ISSUE TITLE
Fails on Ubunutu 20.04 

### ISSUE THREAD

**Issue by MFAshby** [geerlingguy/ansible-role-docker#196]
Tried to install docker & docker-compose on ubuntu 20.04, it failed with the following error:
```
TASK [geerlingguy.docker : Add Docker repository.] **********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
```
failing command 
```
ansible-playbook --ask-become-pass -i localhost --connection=local roles.yml
```

Relevant snipped of roles.yml
```
- hosts: localhost
  roles: 
    - role: geerlingguy.docker
      tags: docker
      become: yes     
      docker_install_compose: true
```
