### ISSUE TITLE
evaluating 'docker_users' as a bare variable

### ISSUE THREAD

**Issue by cojack** [geerlingguy/ansible-role-docker#207]
```
TASK [geerlingguy.docker : include_tasks] ****************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating 'docker_users' as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This feature will be 
removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
then i need to run the whole playbook again becuse Im getting an error on 

```
Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
fatal: [xx.xx.xx.xx]: FAILED! => {
    "changed": false
}
```

where this taks looks like:

```
- name: Run gitlab-runner-docker-cleanup
  docker_container:
    name: gitlab-runner-docker-cleanup
    image: quay.io/gitlab/gitlab-runner-docker-cleanup
    state: started
    restart_policy: always
    env:
      LOW_FREE_SPACE: "10G"
      EXPECTED_FREE_SPACE: "30G"
      DEFAULT_TTL: "30m"
      USE_DF: "1"
      CHECK_INTERVAL: "1m"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
```

idk why but next run works fine
