### ISSUE TITLE
DOCKER iptables chain problem when used with geerlingguy.firewall

### ISSUE THREAD

**Issue by ps-aux** [geerlingguy/ansible-role-docker#21]
I have a simple playbook

```
- hosts: virt
  vars:
    firewall_allowed_tcp_ports:
    - "22"
  roles:
    - firewall
    - docker
```

After successfull completion running `docker run -p 1234:1234 hello-world` results in:

`docker: Error response from daemon: driver failed programming external connectivity on endpoint amazing_mestorf (3dcbb599298bbd13e3769ef93d5659c25185f143f819250dc9a67f80caefe31c):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 1234 -j ACCEPT: iptables: No chain/target/match by that name. (exit status 1)).`

Workaround is to restart the Docker service
