### ISSUE TITLE
"Add Docker GPG key" failing on CentOS7 running as a sudo-enabled user (missing 'become'?)

### ISSUE THREAD

**Issue by dyasny** [geerlingguy/ansible-role-docker#213]
Playbook:
```
- hosts: myhosts
  vars:
    docker_users:
      - "{{ ansible_user }}"
  roles:
    - geerlingguy.docker
```

Run result:

```
fatal: [10.1.12.59]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "fingerprint": null,
            "key": "https://download.docker.com/linux/centos/gpg",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "error: cannot open Packages index using db5 - Permission denied (13)\nerror: cannot open Packages database in /var/lib/rpm\nerror: /tmp/tmpLMzn3W: key 1 import failed.\n"
}
```

After adding `become: true` to all the tasks in setup-RedHat.yml fixes this (but brings out the missing permisisons in the subsequent tasks). I'd like to avoid doing a global `become: true` across the entire playbook

**Comment by robcxyz** [comment]
Little late, but you can escalate to root on a role-wise basis. 

```yaml
- hosts: myhosts
  vars:
    docker_users:
      - "{{ ansible_user }}"
  roles:
    - role: geerlingguy.docker
      become: true
```
