### ISSUE TITLE
Reboot required when when using docker_users feature

### ISSUE THREAD

**Issue by domenicbove** [geerlingguy/ansible-role-docker#237]
I am observing on ubuntu and centos amis, that after running your role:

```
- name: Prepare
  hosts: all
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ansible_user}}"
      become: yes
```

A later playbook which has `/usr/local/bin/docker-compose up -d` without `become:true` fails with:
```
Couldn't connect to Docker daemon at http+docker://localhost - is it running?\n\nIf it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

This is all resolved by doing:
```
- name: Prepare
  hosts: all
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ansible_user}}"
      become: true

- name: Prepare
  hosts: all
  tasks:
    - name: Reboot of host so ansible_user will work with Docker
      reboot:
      become: true

    - name: Wait for SSH
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: SSH
        delay: 10
        timeout: 320
      connection: local
```

Do you think the role should be handling the reboot?
