### ISSUE TITLE
Setting the docker_version variable does not update the docker-ce-cli and docker-ce-rootless-extras packages

### ISSUE THREAD

**Issue by JordiRoman** [geerlingguy/ansible-role-docker#251]
Setting the docker_version variable and running the role on a playbook updates the docker-ce package to the indicated version, but does not update the docker-ce-cli and docker-ce-rootless-extras packages to the same version.

```
root@aules.sbd.uab.cat:~# dpkg -l docker-ce*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version                     Architecture Description
+++-=========================-===========================-============-=====================================================
ii  docker-ce                 5:20.10.2~3-0~debian-buster amd64        Docker: the open-source application container engine
ii  docker-ce-cli             5:20.10.1~3-0~debian-buster amd64        Docker CLI: the open-source application container eng
ii  docker-ce-rootless-extras 5:20.10.1~3-0~debian-buster amd64        Rootless support for Docker.
```

**Comment by ozboss** [comment]
Also when installing a specific version in the first place the version only applies to "docker-ce".

```
# dpkg -l docker-ce*

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version                    Architecture Description
+++-=========================-==========================-============-========================================================
ii  docker-ce                 5:20.10.1~3-0~ubuntu-focal amd64        Docker: the open-source application container engine
ii  docker-ce-cli             5:20.10.6~3-0~ubuntu-focal amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras 5:20.10.6~3-0~ubuntu-focal amd64        Rootless support for Docker.
```

**Comment by ozboss** [comment]
@geerlingguy will you accept a PR?

**Comment by rajaniesh** [comment]
I still see this issue. When this issue will be closed?

**Comment by sakthimaan** [comment]
@rajaniesh @ozboss @JordiRoman 
refer below yaml snippet to rectify this issue

```yaml
    - role: ansible-role-docker
      vars:
        - docker_package_state: latest
        - docker_package:
            - "docker-{{ docker_edition }}"
            - "docker-{{ docker_edition }}-cli"
            - "docker-{{ docker_edition }}-rootless-extras"
   ```
