### ISSUE TITLE
Cannot find Docker python SDK even though its installed.

### ISSUE THREAD

**Issue by marvinrabe** [geerlingguy/ansible-role-docker#273]
On a fresh Vagrant machine with `geerlingguy/centos7` (Unchanged Vagrantfile Configuration) with this Playbook:

```yml
- hosts: all
  become: yes

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Login to Docker registry
      community.docker.docker_login:
        registry_url: ghcr.io
        state: present
        username: REDACTED
        password: REDACTED
```

I get this Error:

```
TASK [geerlingguy.pip : Ensure pip_install_packages are installed.] ****************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'docker'})

...

TASK [Login to Docker registry] ****************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on localhost.localdomain's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named requests.exceptions"}
```

Even though the Docker SDK for Python was installed by `pip_install_packages` successfully.
