### ISSUE TITLE
add centos-extras because of missing packages

### ISSUE THREAD

**Issue by snoopotic** [geerlingguy/ansible-role-docker#282]
Hi I would Add between here:
https://github.com/geerlingguy/ansible-role-docker/blob/e0fc26eb36f1ef591ca1519d6b7d22039ba68fbb/tasks/setup-RedHat.yml#L22

as follows:

```
- name: Add Centos-Extras Repo 
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'centos-extras'
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'name', value: 'CentOS extras - $basearch' }
    - { option: 'baseurl', value: 'http://mirror.centos.org/centos/7/extras/x86_64' }
    - { option: 'enabled', value: '1' }
    - { option: 'gpgcheck', value: '0' }
 ```
But this solution is so ugly I just wanted to file an issue first to discuss it...
See corresponding problem:
https://stackoverflow.com/questions/65878769/cannot-install-docker-in-a-rhel-server

Do you have a better idea? currently this works. 😅
