### ISSUE TITLE
Add KDE Neon Support

### ISSUE THREAD

**Issue by Kerjox** [geerlingguy/ansible-role-docker#299]
### `ansible_distribution` variable is wrong

> Tested with KDE Neon 5.22.5

The `ansible_distribution` variable should be `ubuntu`, not `KDE neon`, otherwise, the installation would fail on step name **Add Docker apt key** on the `setup-Debian.yml` file, due to the URL that hit doesn't exist.

- This URL doesn't exist `https://download.docker.com/linux/kde neon/gpg`
- This other one yes `https://download.docker.com/linux/ubuntu/gpg`

**Comment by mxr576** [comment]
The same issue exists on other Ubuntu flavors. like LinuxMint (Cinnamon). I had to handle the same error and I did it differently than in PR #300.

` /etc/os-release` already defines in ID_LIKE that this is `ubuntu` basically. See: https://www.commandlinux.com/man-page/man5/os-release.5.html

```
cat /etc/os-release                           
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```
so I added this pre_task to my playbook as a hotfix

```
  pre_tasks:
    - name: Identify Ubuntu in an Ubuntu flavor OS like LinuxMint
      ansible.builtin.shell: sed 's/ID_LIKE=//;t;d' /etc/os-release
      register: distribution_by_os_release
    - name: Fix ansible_distribution on an Ubuntu flavor
      set_fact:
        ansible_distribution: "{{ distribution_by_os_release.stdout }}"
      when: distribution_by_os_release.stdout is defined
```

there could be better approaches, but this information should be dynamically set/corrected, instead of being hardcoded as in #300. @geerlingguy what do you think?

Related: https://github.com/ansible/ansible/issues/21706

**Comment by mxr576** [comment]
If KDE Neon has this os-release file then my code needs further adjustments, like splitting the ID_LIKE string and using the first item.
https://githubmemory.com/repo/JacksonKearl/testissues/issues/38968

**Comment by webchi** [comment]
First pretask with quote remove and os split
```
  pre_tasks:
    - name: Identify Ubuntu on an Ubuntu flavor OS like LinuxMint
      ansible.builtin.shell: sed 's/ID_LIKE=//;t;d' /etc/os-release | tr -d '"' | cut -d " " -f 1
      register: distribution_by_os_release
```
