### ISSUE TITLE
Fetch "latest" tag for docker-compose

### ISSUE THREAD

**Issue by Shanduur** [geerlingguy/ansible-role-docker#318]
As `docker-compose` reached version 2 some time ago, this might be a good option to change few default things:

1. Set `docker_compose_version` to `latest`, and fetch the latest, for example using task:
```yml
- name: Get latest release of a public repository
      community.general.github_release:
        user: docker
        repo: compose
        action: latest_release
      register: latest_release
```
which depends on python3 library `github3.py`, or with plain shell, which requires `sed`, `grep` and `curl`:
```sh
curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
```
2. Change default `docker_compose_path` to ` /usr/libexec/docker/cli-plugins/docker-compose`?

**Comment by alexschomb** [comment]
Thanks for your issue and hints, I think this should be referenced to #304.

I utilized your approach for a temporary workaround (as long as 'latest' is not supported yet) in the following way:

```
# site.yml
---
- hosts: dockerservers
  roles:
    - role: geerlingguy.pip
      become: yes

- hosts: dockerservers
  vars_files:
    - vars/docker.yml
  pre_tasks:
    - name: Get latest release of docker-compose.
      community.general.github_release:
          user: docker
          repo: compose
          action: latest_release
      register: docker_compose_latest_release
  roles:
    - role: geerlingguy.docker
      become: yes
```

```
# vars/docker.yml
---
docker_package_state: latest
docker_compose_version: "{{ docker_compose_latest_release.tag }}"
docker_compose_path: "/usr/libexec/docker/cli-plugins/docker-compose"
```

```
# group_vars/dockerservers.yml
---
pip_install_packages:
    - name: docker
    - name: github3.py
```
