### ISSUE TITLE
Wrong version of docker-compose is installed

### ISSUE THREAD

**Issue by UntouchedWagons** [geerlingguy/ansible-role-docker#322]
My main.yml file:

```docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose: true
docker_compose_version: "1.29.2"
docker_compose_path: /usr/local/bin/docker-compose
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: True
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

docker_users:
  - jordan
```

But for some reason version 1.26.0 of docker-compose is installed:

```$docker-compose --version
docker-compose version 1.26.0, build d4451659
```
OS is Ubuntu 20.04 Server

**Comment by eradan** [comment]
same problem here!

**Comment by obvionaoe** [comment]
I'm not able to reproduce the issue! @UntouchedWagons could you share your playbook, or the roles you ran with this one? I also couldn't reproduce issue #321

**Comment by UntouchedWagons** [comment]
I assume the yml file is the playbook you're referencing:

```
$ cat install-docker.yml
- hosts: docker
  become: true
  roles:
    - geerlingguy.docker
$ cat inventory
[docker]
dockertest.untouchedwagons.site

```

I can reproduce this 100% of the time.

**Comment by obvionaoe** [comment]
In which file are you overriding the default variables? And which command are you running to apply the playbook?

**Comment by UntouchedWagons** [comment]
In `defaults/main.yml`: 

```
$ cat defaults/main.yml
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_install_compose: true
docker_compose_version: "1.29.2"
docker_compose_path: /usr/local/bin/docker-compose
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: True
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

docker_users:
  - jordan
```

And I run the playbook like so:

```
$ ansible-playbook --ask-become-pass ./install-docker.yml
```

**Comment by obvionaoe** [comment]
You're missing the following variables:

```yaml
docker_compose_arch: x86_64
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ docker_compose_arch }}"

docker_repo_url: https://download.docker.com/linux

docker_yum_repo_url: "{{ docker_repo_url }}/{{ (ansible_distribution == 'Fedora') | ternary('fedora','centos') }}/docker-{{ docker_edition }}.repo"
docker_yum_repo_enable_nightly: '0'
docker_yum_repo_enable_test: '0'
docker_yum_gpg_key: "{{ docker_repo_url }}/centos/gpg"

docker_daemon_options: {}
```

Are you not getting any error messages when running the playbook? I get an error before the role can start installing docker-compose

**Comment by UntouchedWagons** [comment]
I didn't include some of those variables because I'm not using an RPM-based distro. No I'm not getting any errors.

**Comment by obvionaoe** [comment]
But a few of those variables are used in every distro type:

```yaml
docker_compose_arch: x86_64
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ docker_compose_arch }}"

docker_daemon_options: {}
```

**Comment by UntouchedWagons** [comment]
Okay I added those variables and ran the playbook against the test VM

```
$ groups
jordan cdrom floppy sudo audio dip video plugdev netdev
jordan@DockerTest:~$ docker-compose version
docker-compose version 1.26.0, build d4451659
docker-py version: 4.2.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

Still not adding my user to the docker group and docker-compose is still the wrong version.

**Comment by obvionaoe** [comment]
What OS are you running? And have you tried it with a fresh install on the VM?

**Comment by UntouchedWagons** [comment]
I've tried both Ubuntu 20.04 and Debian 11. This current VM is a fresh install.

**Comment by obvionaoe** [comment]
What Ansible version are you using?

**Comment by UntouchedWagons** [comment]
```
r$ ansible-playbook --version
ansible-playbook [core 2.11.2]
  config file = /home/jordan/ansible-docker/ansible.cfg
  configured module search path = ['/home/jordan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jordan/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/jordan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jordan/.local/bin/ansible-playbook
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

**Comment by obvionaoe** [comment]
Hmm, that version should work fine... Have you changed any Ansible defaults in your `ansible.cfg`?

**Comment by UntouchedWagons** [comment]
```
[defaults]
inventory = inventory
private_key_file = ~/.ssh/id_ed25519
deprecation_warnings=False
```

I don't remember why I have deprecation_warnings set to false

**Comment by obvionaoe** [comment]
That shouldn't be the issue... Are you overriding the variables in the geerlingguy.docker/defaults/main.yml file or elsewhere? Maybe Ansible is not detecting the file where you are overriding the variables?

**Comment by UntouchedWagons** [comment]
I don't think I'm overriding the variables elsewhere.

**Comment by obvionaoe** [comment]
But did you go into the defaults/main.yml that came with the role and edited it? Or did you create a new file and copied/edited what you needed? If you created a new file, Ansible is most likely not including it by default

**Comment by UntouchedWagons** [comment]
I made a new file because that's what I understood the instructions to say.

**Comment by obvionaoe** [comment]
And you are right! But for Ansible to recognize those variables you need to edit your playbook to include the file in which you override them!

```yaml
- hosts: docker
  become: true
  vars_files:
    - path/to/var/file.yml
  roles:
    - geerlingguy.docker
```

**Comment by UntouchedWagons** [comment]
Yup that did the trick

```
- hosts: docker
  become: true
  vars_files:
    - defaults/main.yml
  roles:
    - geerlingguy.docker
```

```
$ groups
jordan cdrom floppy sudo audio dip video plugdev netdev docker
$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
