### ISSUE TITLE
Update docker-compose is not working

### ISSUE THREAD

**Issue by Normo** [geerlingguy/ansible-role-docker#342]
When updating the  `docker_compose_version` the role does not install the new version.

## Steps to reproduce
1.  Specify `docker_compose_version` e.g. in `molecule/default/converge.yml`
    ```yaml
    - name: Converge
      hosts: all
      become: true
      vars:
        docker_compose_version: "v2.4.0"
    ```
2. Run `molecule converge` 
3. Log into test instance: `molecule login`
4. Check docker-compose version: `docker-compose version`
5. Exit test instance
6. Update `docker_compose_version`: `docker_compose_version: "v2.4.1"`
2. Run `molecule converge` 
3. Log into test instance: `molecule login`
4. Check docker-compose version again: `docker-compose version`
