### ISSUE TITLE
Feature request - Set proxy enviroment

### ISSUE THREAD

**Issue by jmcarranza** [geerlingguy/ansible-role-docker#36]
Hi, it would be very useful to define the proxy variable for docker.

**Comment by denics** [comment]
Hi @matevarga I have the environment set, but the proxy is not working for me.

**Comment by mxdlx** [comment]
Anyone interested in this can add a template and handle it with Ansible following the [official documentation](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy).

**Comment by Sprinterfreak** [comment]
The point where everything breaks in a proxyed environment is due to a bug, called feature not implemented, in `apt_key`. Ansibles apt_key does not pass required additional command-line parameters to use the proxy from environment.

Possible fix is to *NOT* use apt_key's url parameter at all like so:
```
name: Add Docker apt key.
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/debian/gpg', split_lines=False) }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"
```
