### ISSUE TITLE
Being able to set static version for `docker` package

### ISSUE THREAD

**Issue by mhkarimi1383** [geerlingguy/ansible-role-docker#360]
We need to set static version of `docker` for lots of reasons, if it's okay I will make a PR ;)

**Comment by mhkarimi1383** [comment]
I have done some investigations, we can set that in package name followed by `-` for `yum` and for `apt` we use package name followed by `=`

since we set have our package name configured like below

```yaml
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
```

I don't know if it's okay to overwrite it directly or making tasks more conditional to handle new variable for `version `
