### ISSUE TITLE
Setting hosts in docker_daemon_opts variable on a debian 11 host breaks docker

### ISSUE THREAD

**Issue by zloveless** [geerlingguy/ansible-role-docker#411]
I added a docker directive meant to configure docker to listen on a TCP port (for local development). Docker didn't like that, and complained that I had specified conflicting parameters. The reason is that the systemd unit file for docker specified `-H fd://` and `--containerd=...` in the startup params.

The fix was to add a systemd override config file to modify the startup params which just launches `/usr/bin/dockerd` with no args. I added "containerd" as another docker_daemon_opts entry with the original value from the command line as a workaround.

I'm documenting this here for the future in case someone else runs into this issue. I don't know if the role can fix this directly, without some weird ansible conditional logic lol. So this is probably a low priority.

---
**Current behavior:**

Docker doesn't come back up when certain arguments are added to docker_daemon_opts

**Expected behavior:**

The ansible role has some way to adapt if someone wants to specify an alternative listen host for the docker socket, it would add a systemd override file as described above.

**Comment by epou** [comment]
thanks @sepek for your solution. I've added some more lines into yours to make a little bit more generic and avoid some errors

```yaml
pre_tasks: # see: https://github.com/geerlingguy/ansible-role-docker/issues/411
    - name: Docker - make sure systemd dir exists
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'
        owner: root
        group: root
    - name: Docker - override systemd service unit
      copy:
        dest: '/etc/systemd/system/docker.service.d/override.conf'
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd
        mode: '0755'
        owner: root
        group: root
      register: systemd_changed
    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
      when: systemd_changed.changed
```

hope it helps
