### ISSUE TITLE
Failure when adding docker repository

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [geerlingguy/ansible-role-docker#434]
I am installing the role as follows

```yaml
    - name: Install required ansible-galaxy roles
      local_action: shell ansible-galaxy install -r requirements.yaml --force
```

where

```
$ cat requirements.yaml
- src: geerlingguy.docker
```

and then invoking it

```yaml
    - name: Install docker and docker-compose
      include_role:
        name: geerlingguy.docker
        apply:
          become: yes
      vars:
        docker_compose_path: "/usr/local/bin/docker-compose"
        docker_compose_version: "1.27.4"
```

This fails with the following error

```
│ TASK [geerlingguy.docker : Add Docker repository.]
│ *****************************
│ An exception occurred during task execution. To see the full traceback, use
│ -vvv. The error was: apt_pkg.Error: E:Conflicting values set for option
│ Signed-By regarding source https://download.docker.com/linux/ubuntu/ focal:
│ /etc/apt/trusted.gpg.d/docker.asc != , E:The list of sources could not be
│ read.
```

`ansible` runs on the following machine

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Any suggestions?
