### ISSUE TITLE
no /etc/docker/daemon.json ?

### ISSUE THREAD

**Issue by hsh-it** [geerlingguy/ansible-role-docker#445]
https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/main.yml
```
- name: Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options.
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: restart docker
```

On ubuntu 22.04 clean installation. There is no `/etc/docker/daemon.json` file on system
```
/etc/docker $ ll
total 8
drwxr-xr-x   2 root root 4096 Feb  6 21:13 ./
drwxr-xr-x 112 root root 4096 Feb 15 11:08 ../
```

`Linux 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
