### ISSUE TITLE
Does not work with a non-root user

### ISSUE THREAD

**Issue by iliya-malecki** [geerlingguy/ansible-role-docker#490]
I might be wildly misunderstanding something, but https://github.com/geerlingguy/ansible-role-docker/blob/ffc1374a227fbb1a36415ad4df71b6450d323d8f/tasks/setup-Debian.yml#L26 dies with could not create temporary file for /var/lib/apt/extended_states - mkstemp (13 permission denied). At a first glance, seems like become: true is missing

**Comment by ELLIOTTCABLE** [comment]
I was also surprised to not see `become: true` in the README. (=

**Comment by pythoninthegrass** [comment]
I got around it by calling the role like this:
```yaml
  roles:
    - role: geerlingguy.docker
      vars:
        docker_add_repo: true
        docker_repo_url: https://download.docker.com/linux
        docker_users:
          - "{{ local_user }}"
        docker_daemon_options:
          storage-driver: "vfs"
          log-opts:
            max-size: "100m"
        docker_packages:
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"
          - "docker-buildx-plugin"
          - "docker-compose-plugin"
      become: true
      tags: docker
  tasks:
    - ...
```
