### ISSUE TITLE
Pinned version not honored on initial install (Debian)

### ISSUE THREAD

**Issue by NiklasBeierl** [geerlingguy/ansible-role-docker#505]
When using the following vars:

```yaml
      docker_apt_version: "5:26.1.0-1~debian.12~bookworm"
      docker_packages:
        - "docker-ce={{ docker_apt_version }}"
        - "docker-ce-cli={{ docker_apt_version }}"
        - "containerd.io"
        - "docker-buildx-plugin"
      docker_packages_state: present
```

And running my play on a fresh Debian 12 VM, I get the latest version of docker (currently `28.1.1`) instead of the specified one.
Running the role (without changes) **a second time** then downgrades the packages to the desired version.
