### ISSUE TITLE
Failed to import docker-py 

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-docker#53]
fatal: [174.138.8.0]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}

**Comment by 030** [comment]
https://stackoverflow.com/a/41493058/2777965

**Comment by geerlingguy** [comment]
Are you still getting this error? I haven't seen this on any platforms in my testing, nor in my prod server builds. Can you give a reliable set of steps/config to reproduce?

**Comment by jakubgs** [comment]
Why doesn't this role just install `python-docker` instead of depending on yet another role to install it via `pip`?

**Comment by patrickvale** [comment]
Hi,

I am experiencing this problem when using ansible to start a docker-compose stack on a Hetzner Cloud server. Here's my playbook:

```
---
- hosts: emailservers
  roles:
    - role: geerlingguy.docker
      become: true
      docker_edition: 'ce'
      docker_package_state: present
      docker_install_compose: True
      docker_users:
        - ansible
    - role: docker_mailserver
```

I tried modifying the ansible_python_interpreter (having installed python 2.7 on Ubuntu or using the stock Debian 9 image) by setting an inventory variable :

```
[hcloud]
email.***.io

[emailservers]
email.***.io

[emailservers:vars]
ansible_python_interpreter=/usr/bin/python2.7
```

But I'm still getting this error. The task which the role fails on is:

```
  - name: Start the docker-compose services
    docker_service:
      project_src: "{{ docker_mailserver_config_path }}"
      state: present
```

The very verbose error is

```
The full traceback is:
    File "/tmp/ansible_GGoQWf/ansible_module_docker_service.py", line 458, in <module>
    from compose import __version__ as compose_version

    fatal: [email.***.io]: FAILED! => {
    "changed": false,
    "invocation": {
    "module_args": {
    "api_version": null,
    "build": false,
    "cacert_path": null,
    "cert_path": null,
    "debug": false,
    "definition": null,
    "dependencies": true,
    "docker_host": null,
    "files": null,
    "filter_logger": false,
    "hostname_check": false,
    "key_path": null,
    "nocache": false,
    "project_name": null,
    "project_src": "/tmp/docker-mailserver",
    "pull": false,
    "recreate": "smart",
    "remove_images": null,
    "remove_orphans": false,
    "remove_volumes": false,
    "restarted": false,
    "scale": null,
    "services": null,
    "ssl_version": null,
    "state": "present",
    "stopped": false,
    "timeout": 10,
    "tls": null,
    "tls_hostname": null,
    "tls_verify": null
}
},
    "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"
}
```

**Comment by patrickvale** [comment]
Following the suggestion by @jakubgs I tried adding an apt task to install python-docker, just before starting the compose services, however it returned this error

```
"Unable to load docker-compose. Try `pip install docker-compose`. Error: No module named compose"
```

**Comment by danihodovic** [comment]
@patrickvale 

This is because the docker-compose installation pulls in the binary directly from Github. https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/docker-compose.yml#L16-L20

Since docker-compose isn't installed through pip there is no python compose library to import. Therefore this role doesn't work with `docker_service` which under the hood uses the compose python library.

I suggest you disable the compose install of this role and instead install docker-compose through pip.

```
---
dependencies:
  - role: geerlingguy.docker
    vars:
      docker_package: 'docker-ce=18.03.1~ce-0~ubuntu'
      docker_install_compose: false
```

```
- name: Install docker-compose
  pip:
    name: docker-compose
```

**Comment by kzap** [comment]
I found the above solution to work because of
```yaml
- name: Install docker-compose
  pip:
    name: docker-compose
```

instead of using the `geerlingguy.pip` role since the `pip` module will use the default pip that Ansible is using whereas `geerlingguy.pip` will use `pip` as the executor by default and this may not be obvious
