### ISSUE TITLE
become: true needed on most of the tasks

### ISSUE THREAD

**Issue by hiucimon** [geerlingguy/ansible-role-docker#65]
I have to assume you run your ansible as root. When I try to run your scripts, it all fails with permissions. I have to update each task with become: true, then it all runs perfect.

**Comment by geerlingguy** [comment]
@hiucimon yes, I either run my playbook with `become: yes`, or I call the role with `become: yes`, e.g.:

```yaml
  roles:
    - name: geerlingguy.docker
      become: yes
```
