### ISSUE TITLE
Invoking "apt" only once while using a loop via squash_actions is deprecated

### ISSUE THREAD

**Issue by gebn** [geerlingguy/ansible-role-docker#77]
Using version 2.5.0, I receive the following while executing the role using the `devel` branch:

    TASK [geerlingguy.docker : Ensure dependencies are installed.] ***********************************************************************************************************************
    [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: {{ item 
    }}`, please use `name: [u'apt-transport-https', u'ca-certificates']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by 
    setting deprecation_warnings=False in ansible.cfg.
    ok: [hostname] => (item=[u'apt-transport-https', u'ca-certificates'])

The fix looks trivial, and will actually make the role more efficient. From the `apt` module [notes](https://docs.ansible.com/ansible/latest/modules/apt_module.html#notes):

> When used with a *loop*: each package will be processed individually, it is much more efficient to pass the list directly to the *name* option.

**Comment by MaartenW** [comment]
The examples in the documentation (2.7) still use list items. No examples of the new style.

Q: Do we need to add the "u" before the single quote?

**Comment by gebn** [comment]
@chevdor I don’t quite follow - if you feel inclined, you can comment out lines in the `name` list in the same way you could in `with_items` before.

**Comment by martindines** [comment]
`
- name: "Install dependencies"
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
      - libnss3
      - libasound2
      - xcb
      - xinit
`

becomes

`
- name: "Install dependencies"
  apt:
    pkg:
      - libnss3
      - libasound2
      - xcb
      - xinit
    state: present
`

**Comment by analbeard** [comment]
@chevdor:

I don't use this module but I came across this issue whilst googling the deprecation message. I agree - I don't want to have all the packages listed on a single line as it's not as flexible and isn't as obvious as to what's changed when you diff two commits.

I discovered that as per [the porting guide](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.7.html#using-a-loop-on-a-package-module-via-squash-actions) you can make a list of the packages as a separate variable and then pass that variable to the apt module, like so:

```yaml
vars:
  packages:
    - ubuntu-mate-core    
    - ubuntu-mate-desktop
#    - imagemagick          
    - xrdp

tasks:
  - name: "Install dependencies"
    apt:
      pkg: "{{ packages }}"
      state: present
```

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Please reopen this bug.
What about the situation where some packages have versions ? (i.e. when `apt` module options depend on the package name)

```yaml
- name: install extensions
  apt:
    name: '{{ item }}'
    state: '{{ (item is match(".*=.*")) | ternary("present", "latest") }}'
    force: yes
  with_items:
    - package1
    - package2=1.2.3-r2
    - package3=3.2.1-r3
    - package4
```

I think we don't need in such improvement. Please roll it back.
