### ISSUE TITLE
Role is always deleting and reinstalling Docker compose

### ISSUE THREAD

**Issue by nathanperkins** [geerlingguy/ansible-role-docker#88]
This role seems to delete and reinstall Docker Compose every time on both a macOS 10.13.6 target and a Centos 7 target.

```
TASK [geerlingguy.docker : Delete existing docker-compose version if it's different.] *************
changed: [hostname]

TASK [geerlingguy.docker : Install Docker Compose (if configured).] *******************************
changed: [hostname]
```

Not sure if I have something configured incorrectly. These are the only configurations that I think are related to the role:

```
# geerlingguy.docker settings
pip_install_packages:
  - name: docker
  - name: docker-compose
docker_users:
  - user1
  - user2
```

Let me know what kind of other information you'd like me to share.
