### ISSUE TITLE
Feature Request: allow override of dockerd options 

### ISSUE THREAD

**Issue by robbyoconnor** [geerlingguy/ansible-role-docker#90]
I love your Ansible Roles -- but the major no-go for me is the fact I can't override the storage driver easily.

**Comment by llbbl** [comment]
```
# defaults
docker_default_config:
  storage-driver: overlay2
  log-level: info

# playbook
- name: apply default daemon config
  set_fact:
    docker_json: "{{ docker_default_config | combine(docker_config | default({})) }}"

- name: ensure daemon config file is present
  copy:
    content: |
      {{ docker_json | to_nice_json(indent=2) }}
    dest: /etc/docker/daemon.json
  notify: restart docker

```

how mongrelion is doing it.
